package com.alchemedy.pharasnap.models;

public enum TutorialAction {
    PAUSE_TUTORIAL,
    TAP_WIDGET_BUTTON,
    GENERAL_FORHIBIDDEN_ACTION_ON_TUTORIAL,
    MOVE_WIDGET_BUTTON,
    WIDGET_MOVE_FINISHED,
    MULTIPLE_TEXT_SELECT,
    BOTTOM_BAR_SELECT,
    MODAL_OPENED,
    MODAL_CLOSE,
    MODAL_CLOSED,
    ERASE_ALL_SELECTIONS,
    LONG_PRESS_WORD,
    TAP_IMAGE_WITH_CONTENT_DESCRIPTION,
    SELECT_HIDDEN_TEXT,
    MOVE_BOTTOM_BAR,
    MOVE_FINISHED_BOTTOM_BAR,
    OPEN_QUICK_SETTINGS,
    SELECT_RECENT_ITEM,
    STOP_WIDGET,
    SELECT_TEXT_ONLY_MODE,
    NEXT,
    SWITCH_MODE,
    PICTURE_SELECT,
    HISTORY_BUTTON_SELECT
}
